### ISSUE TITLE
Bright black in Terminal is too dark

### ISSUE THREAD

**Issue by aliebuck** [dracula/nova#1]
I raised this originally on [dev.panic.com](https://dev.panic.com/), however it seems my issue was removed 😕. 

It appears that the bright black color for Terminal is not the correct color as it's too dark. For example:

**Current Behaviour (Nova)**

<img width="207" alt="Screen Shot 2020-11-22 at 12 23 20" src="https://user-images.githubusercontent.com/830470/99889817-8fec4800-2cbd-11eb-85bf-fab07157ba0a.png">

**Expected Behaviour ([Terminal.app](https://draculatheme.com/terminal))**

<img width="203" alt="Screen Shot 2020-11-22 at 12 23 02" src="https://user-images.githubusercontent.com/830470/99889819-95e22900-2cbd-11eb-8320-51ed94f9a71c.png">

**Environment**

* Nova version: ~~3 (218855)~~ 3.1 (221256)
* Extension version: 1.4
* macOS version: 11.0.1 (20B29)

**Comment by bdielman** [comment]
@jacobbuck - Thanks for pointing this out! I'll get this fixed in the next release.

**Comment by aliebuck** [comment]
Looks great ❤️
