### ISSUE TITLE
Boarders and dividers low contrast 

### ISSUE THREAD

**Issue by aaronmoodie** [dracula/nova#2]
Not sure if this was deliberate, but the borders on the main window UI and the dividers in the side bar are low contrast and difficult to see. Would be great to add some more distinction here. 

Dracula theme
<img width="363" alt="image" src="https://user-images.githubusercontent.com/105030/100026238-89390e80-2e3e-11eb-806c-9c5497ba5089.png">

Default dark theme
<img width="363" alt="image" src="https://user-images.githubusercontent.com/105030/100027395-d322f400-2e40-11eb-8fd5-fb47d9282ab8.png">

**Comment by bdielman** [comment]
Thanks, @aaronmoodie! I'll take a look at fixing this in the next release. I like how it's done for both the Palette and Neon themes with one consistent border color so I'll do something similar here.

<img width="323" alt="Screen Shot 2020-11-24 at 4 13 54 PM" src="https://user-images.githubusercontent.com/94547/100152277-73dcd800-2e70-11eb-9664-7519ea361a19.png">

**Comment by aaronmoodie** [comment]
Thanks @bdielman! Sidebar looks great! I actually don't mind the darker divider at top in the main window. It makes the nav bar seem like it's slightly elevated.

**Comment by bdielman** [comment]
I thought about that, but it's still really hard to discern the borders in the titlebar. There's a lot about the window theme that will need to be brought closer to spec, so these styles will evolve over time.
