### ISSUE TITLE
Dracula Pro

### ISSUE THREAD

**Issue by robb-j** [dracula/nova#7]
Hi, this is my daily driver theme for Nova, thanks! I was wondering if there is any chance of getting Dracula Pro support for Nova?

Thanks,
Rob

**Comment by bdielman** [comment]
I'll defer to @zenorocha on this issue. 🧛

**Comment by BryanSchuetz** [comment]
Another vote for pro on Nova. Really want to use the Alucard variant here but no chance of it as things are now.

**Comment by bdielman** [comment]
I'm currently maintaining this version of Dracula for Nova. As for creating a Nova port for Dracula Pro I'll reach out the core team to see if it's on roadmap
